//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.03.29 at 11:06:28 AM CEST
//


package nl.broservices.xsd.cptcommon.v_1_1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import net.opengis.gml.v_3_2_1.AbstractFeatureType;
import net.opengis.gml.v_3_2_1.FeaturePropertyType;
import net.opengis.gml.v_3_2_1.ReferenceType;
import net.opengis.gml.v_3_2_1.TimeInstantPropertyType;
import net.opengis.gml.v_3_2_1.TimePeriodPropertyType;
import net.opengis.om.v_2_0.NamedValuePropertyType;
import net.opengis.om.v_2_0.OMProcessPropertyType;
import net.opengis.om.v_2_0.ObservationContextPropertyType;


/**
 * <p>Java class for CptObservationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CptObservationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.opengis.net/om/2.0}OM_ObservationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.opengis.net/om/2.0}OM_CommonProperties"/&gt;
 *         &lt;element ref="{http://www.broservices.nl/xsd/cptcommon/1.1}cptResult"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CptObservationType", propOrder = {
    "type",
    "relatedObservation",
    "phenomenonTime",
    "resultTime",
    "validTime",
    "procedure",
    "parameter",
    "observedProperty",
    "featureOfInterest",
    "cptResult"
})
@XmlSeeAlso({
    ConePenetrationTestType.class
})
public class CptObservationType  extends AbstractFeatureType implements Serializable, ToString2
{

    @XmlElement(namespace = "http://www.opengis.net/om/2.0")
    protected ReferenceType type;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0")
    protected List<ObservationContextPropertyType> relatedObservation;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0", required = true)
    protected TimeInstantPropertyType phenomenonTime;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0", required = true)
    protected TimeInstantPropertyType resultTime;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0")
    protected TimePeriodPropertyType validTime;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0", required = true, nillable = true)
    protected OMProcessPropertyType procedure;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0")
    protected List<NamedValuePropertyType> parameter;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0", required = true, nillable = true)
    protected ReferenceType observedProperty;
    @XmlElement(namespace = "http://www.opengis.net/om/2.0", required = true, nillable = true)
    protected FeaturePropertyType featureOfInterest;
    @XmlElement(required = true)
    protected ConePenetrationTestResultType cptResult;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *
     */
    public ReferenceType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *
     */
    public void setType(ReferenceType value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the relatedObservation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedObservation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedObservation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservationContextPropertyType }
     *
     *
     */
    public List<ObservationContextPropertyType> getRelatedObservation() {
        if (relatedObservation == null) {
            relatedObservation = new ArrayList<ObservationContextPropertyType>();
        }
        return this.relatedObservation;
    }

    public boolean isSetRelatedObservation() {
        return ((this.relatedObservation!= null)&&(!this.relatedObservation.isEmpty()));
    }

    public void unsetRelatedObservation() {
        this.relatedObservation = null;
    }

    /**
     * Gets the value of the phenomenonTime property.
     *
     * @return
     *     possible object is
     *     {@link TimeInstantPropertyType }
     *
     */
    public TimeInstantPropertyType getPhenomenonTime() {
        return phenomenonTime;
    }

    /**
     * Sets the value of the phenomenonTime property.
     *
     * @param value
     *     allowed object is
     *     {@link TimeInstantPropertyType }
     *
     */
    public void setPhenomenonTime(TimeInstantPropertyType value) {
        this.phenomenonTime = value;
    }

    public boolean isSetPhenomenonTime() {
        return (this.phenomenonTime!= null);
    }

    /**
     * Gets the value of the resultTime property.
     *
     * @return
     *     possible object is
     *     {@link TimeInstantPropertyType }
     *
     */
    public TimeInstantPropertyType getResultTime() {
        return resultTime;
    }

    /**
     * Sets the value of the resultTime property.
     *
     * @param value
     *     allowed object is
     *     {@link TimeInstantPropertyType }
     *
     */
    public void setResultTime(TimeInstantPropertyType value) {
        this.resultTime = value;
    }

    public boolean isSetResultTime() {
        return (this.resultTime!= null);
    }

    /**
     * Gets the value of the validTime property.
     *
     * @return
     *     possible object is
     *     {@link TimePeriodPropertyType }
     *
     */
    public TimePeriodPropertyType getValidTime() {
        return validTime;
    }

    /**
     * Sets the value of the validTime property.
     *
     * @param value
     *     allowed object is
     *     {@link TimePeriodPropertyType }
     *
     */
    public void setValidTime(TimePeriodPropertyType value) {
        this.validTime = value;
    }

    public boolean isSetValidTime() {
        return (this.validTime!= null);
    }

    /**
     * Gets the value of the procedure property.
     *
     * @return
     *     possible object is
     *     {@link OMProcessPropertyType }
     *
     */
    public OMProcessPropertyType getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     *
     * @param value
     *     allowed object is
     *     {@link OMProcessPropertyType }
     *
     */
    public void setProcedure(OMProcessPropertyType value) {
        this.procedure = value;
    }

    public boolean isSetProcedure() {
        return (this.procedure!= null);
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamedValuePropertyType }
     *
     *
     */
    public List<NamedValuePropertyType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<NamedValuePropertyType>();
        }
        return this.parameter;
    }

    public boolean isSetParameter() {
        return ((this.parameter!= null)&&(!this.parameter.isEmpty()));
    }

    public void unsetParameter() {
        this.parameter = null;
    }

    /**
     * Gets the value of the observedProperty property.
     *
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *
     */
    public ReferenceType getObservedProperty() {
        return observedProperty;
    }

    /**
     * Sets the value of the observedProperty property.
     *
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *
     */
    public void setObservedProperty(ReferenceType value) {
        this.observedProperty = value;
    }

    public boolean isSetObservedProperty() {
        return (this.observedProperty!= null);
    }

    /**
     * Gets the value of the featureOfInterest property.
     *
     * @return
     *     possible object is
     *     {@link FeaturePropertyType }
     *
     */
    public FeaturePropertyType getFeatureOfInterest() {
        return featureOfInterest;
    }

    /**
     * Sets the value of the featureOfInterest property.
     *
     * @param value
     *     allowed object is
     *     {@link FeaturePropertyType }
     *
     */
    public void setFeatureOfInterest(FeaturePropertyType value) {
        this.featureOfInterest = value;
    }

    public boolean isSetFeatureOfInterest() {
        return (this.featureOfInterest!= null);
    }

    /**
     * Gets the value of the cptResult property.
     *
     * @return
     *     possible object is
     *     {@link ConePenetrationTestResultType }
     *
     */
    public ConePenetrationTestResultType getCptResult() {
        return cptResult;
    }

    /**
     * Sets the value of the cptResult property.
     *
     * @param value
     *     allowed object is
     *     {@link ConePenetrationTestResultType }
     *
     */
    public void setCptResult(ConePenetrationTestResultType value) {
        this.cptResult = value;
    }

    public boolean isSetCptResult() {
        return (this.cptResult!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            ReferenceType theType;
            theType = this.getType();
            strategy.appendField(locator, this, "type", buffer, theType, this.isSetType());
        }
        {
            List<ObservationContextPropertyType> theRelatedObservation;
            theRelatedObservation = (this.isSetRelatedObservation()?this.getRelatedObservation():null);
            strategy.appendField(locator, this, "relatedObservation", buffer, theRelatedObservation, this.isSetRelatedObservation());
        }
        {
            TimeInstantPropertyType thePhenomenonTime;
            thePhenomenonTime = this.getPhenomenonTime();
            strategy.appendField(locator, this, "phenomenonTime", buffer, thePhenomenonTime, this.isSetPhenomenonTime());
        }
        {
            TimeInstantPropertyType theResultTime;
            theResultTime = this.getResultTime();
            strategy.appendField(locator, this, "resultTime", buffer, theResultTime, this.isSetResultTime());
        }
        {
            TimePeriodPropertyType theValidTime;
            theValidTime = this.getValidTime();
            strategy.appendField(locator, this, "validTime", buffer, theValidTime, this.isSetValidTime());
        }
        {
            OMProcessPropertyType theProcedure;
            theProcedure = this.getProcedure();
            strategy.appendField(locator, this, "procedure", buffer, theProcedure, this.isSetProcedure());
        }
        {
            List<NamedValuePropertyType> theParameter;
            theParameter = (this.isSetParameter()?this.getParameter():null);
            strategy.appendField(locator, this, "parameter", buffer, theParameter, this.isSetParameter());
        }
        {
            ReferenceType theObservedProperty;
            theObservedProperty = this.getObservedProperty();
            strategy.appendField(locator, this, "observedProperty", buffer, theObservedProperty, this.isSetObservedProperty());
        }
        {
            FeaturePropertyType theFeatureOfInterest;
            theFeatureOfInterest = this.getFeatureOfInterest();
            strategy.appendField(locator, this, "featureOfInterest", buffer, theFeatureOfInterest, this.isSetFeatureOfInterest());
        }
        {
            ConePenetrationTestResultType theCptResult;
            theCptResult = this.getCptResult();
            strategy.appendField(locator, this, "cptResult", buffer, theCptResult, this.isSetCptResult());
        }
        return buffer;
    }

}
